// Explicit reviewed preparation. Browser tests only read the resulting fixed archive.
import { execFileSync } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { exportLeague } from '@fantasy/cli/export';
import { leaguePublicationFixture } from '@fantasy/cli/testing';
import { leagueFixture } from '@fantasy/samples/testing';
import { savePublicFixtures } from './publication-fixtures.ts';

const temporary = await mkdtemp(join(tmpdir(), 'fantasy-league-fixture-'));
try {
  const source = {
    sha: execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(),
    node: process.versions.node,
    platform: 'linux' as const,
    arch: 'x64' as const,
  };
  const fixture = await leaguePublicationFixture(join(temporary, 'run'), {
    definition: await leagueFixture(3, 2),
    size: 12,
    source,
  });
  const target = join(temporary, 'public');
  const partial = await exportLeague(
    fixture.plan,
    fixture.partitions,
    fixture.completed.slice(0, 1),
    target,
  );
  const complete = await exportLeague(fixture.plan, fixture.partitions, fixture.completed, target);
  if (partial.resolved !== 12 || complete.resolved !== 24 || complete.status !== 'formal')
    throw new Error('Unexpected league fixture calculation');
  await savePublicFixtures(target, 'apps/web/test-fixtures/league', {
    source,
    generator:
      'node --import ./apps/api/node_modules/tsx/dist/loader.mjs e2e/generate-league-fixtures.ts',
    policy:
      'Three identical real characters, two fields, two seeds and exchanged placements: 24 real 20-step battles. First snapshot omits one 12-slot partition, then all results are published. Old snapshot and pending rows are retained. These fixed bytes are never regenerated by tests.',
    partial: partial.snapshot,
    complete: complete.snapshot,
  });
} finally {
  await rm(temporary, { recursive: true, force: true });
}
